#!/bin/sh

while true
do
    curl --header "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:37.0) Gecko/20100101 Firefox/37.0" --data "action=authenticate&login=LOGIN&password=PASSWORD&policy_accept=false" https://controller.mobile.lan/portal_api.php
    echo "\n"
    sleep 600
done
